### ISSUE TITLE
Single-Page Applications worksheet: Typo

### ISSUE THREAD

**Issue by JoseUusitalo** [covcom/205CDE#13]
Under the **Event Handlers** heading the following lines are referring to function calls on lines 3 and 4 in the **simple_dom.js**, but line 4 is empty and the function call on line 3 is probably not the one being referred to here.

> Notice the two different ways the functions are called by the event handler on line 3 and line 4. Can you understand the different syntax used?

I believe the correct line numbers are 5 and 6. The lines are also incorrectly referenced later in the worksheet.

**Comment by erja** [comment]
Corrected typos.
