### ISSUE TITLE
Unit Testing worksheet: Missing semicolon in given code

### ISSUE THREAD

**Issue by JoseUusitalo** [covcom/205CDE#14]
There's a semicolon missing from the code for the notes object given in the worksheet.

> ``` JS
> var notes = (function() {
>   return {
>     add: function(note) {},
>     remove: function(index) {},
>     count: function() {},
>     list: function() {},
>     find: function(str) {},
>     clear: function() {}
>     } /* Missing semicolon */
> }());
> ```

And later:

> ``` JS
> var notes = (function() {
>     var list = [];
>     return {
>         add: function(note) {
>           var item = {timestamp: Date.now(), text: note};
>             list.push(item);
>             return true;
>         },
>       remove: function(index) {},
>       count: function() {
>           return list.length;
>       },
>       list: function() {},
>       find: function(str) {},
>       clear: function() {}
>     } /* Also missing from here */
> }());
> ```

**Comment by erja** [comment]
Check ;)
