### ISSUE TITLE
Testing with PHPUnit

### ISSUE THREAD

**Issue by iikoo2** [covcom/205CDE#15]
Newest PHPUnit doesn't work because it needs at least PHP 5.6 and Codio has PHP 5.5.15. Also sudo command is not supported, so you have to use some local directory, for example /home/codio/.parts/autoparts/bin. It's also described in $PATH. 

Also you have to download old version of PHPUnit (phpunit-old.phar). So here it goes:

```
$ wget https://phar.phpunit.de/phpunit-old.phar 
$ chmod +x phpunit-old.phar
$ mv phpunit-old.phar /home/codio/.parts/autoparts/bin/phpunit
$ phpunit --version
```

**Comment by kamaj** [comment]
Thank you Ilpo, this is updated to our repo.
