### ISSUE TITLE
Multiple labs: worksheet code formatting

### ISSUE THREAD

**Issue by JoseUusitalo** [covcom/205CDE#16]
These examples are from the **Introduction to PHP** worksheet.

Several worksheets have bad/nonexistent code formatting, like for example:

> Printing out variable values using a non-interpreted string looks like this: print '
> Values '.$number.' and '.$f_number.'
> ';

It would be much clearer if a PHP code block was used:

> Printing out variable values using a non-interpreted string looks like this:
> 
> ``` php
> print 'Values '.$number.' and '.$f_number.'.';
> ```

It would also help the readability if Markdown inline code blocks were used elsewhere in the worksheets as well. Like for example here:

> Examples: `$str = "Writing PHP is cool"; $printed = "Values $number and $f_number"; $str2 = 'This is also a string';`

Adding the language name at the start of a code block to add syntax highlighting would also be quite nice. At the moment none of the code blocks have syntax highlighting.

**Comment by erja** [comment]
Good point, I hope I found most of them.
