### ISSUE TITLE
Testing PHP with PHPUnit: Typo?

### ISSUE THREAD

**Issue by JoseUusitalo** [covcom/205CDE#18]
Here we are instructed to copy the code into a `src/Money.php` file.

> The next code snippet is a simple class called Money, which has one attribute called amount. (src/Money.php)

Later we are to execute this command:

> `phpunit --bootstrap src/autoload.php tests/MoneyTest`

The file `src/autoload.php` does not exist nor have we been instructed to make it. Changing it to `Money.php` runs the test correctly.

**Comment by erja** [comment]
You could have autoload.php telling which files to include (this is now explained in the worksheet). Or you can just list the files after --bootstrap.
