### ISSUE TITLE
Model-View-Controller issues

### ISSUE THREAD

**Issue by JoseUusitalo** [covcom/205CDE#22]
Typo and the sentence also needs rewording.

> You might need sometimes also a **destrunctor** (__destruct()), which deletes an object.

These links need to be formatted into lists:

> Wikipedia MVC Architecture MVC for Noobs

and:

> Choosing a Web Framework/Language Combo for the Next Decade 15 Most Important Considerations when Choosing a Web Development Framework 10 criteria for choosing the correct framework Choosing A Web Framework How to choose a web framework and be surprised

This is just silly. The word you were looking for is "nowadays".

> **Current days**, Model View Controller(MVC) is the most popular design pattern in software development.

In English the apostrophe is used to denote possessive case:

> With it you will find out what is **MVC:s** idea and how CodeIgniter works.

Typo. It would also be nice if a direct link to the CodeIgniters tutorial was provided. Is this the one? http://tutorialcodeigniter.com/

> Go through GodeIgniters tutorial

Edit: It is more likely this one isn't it: http://www.codeigniter.com/user_guide/tutorial/index.html

~~I had to change this line:~~

``` php
$config['uri_protocol'] = 'REQUEST_URI';
```

~~in `CodeIgniter-3.0.3/application/config/config.php` to this:~~

``` php
$config['uri_protocol'] = 'QUERY_STRING';
```

~~for CodeIgniter to successfully generate the example `index.php`. This is not mentioned in the worksheet or the CodeIgniter tutorial.~~

Edit 2: I was unable to finish the first static pages part of the CodeIgniter tutorial so I reinstalled php5, php5-apache2, and mysql on my box and now everything works. I did not need to change the URI protocol either.

**Comment by iikoo2** [comment]
Corrections done...
