### ISSUE TITLE
Codeigniter and RESTful API worksheet minor corrections

### ISSUE THREAD

**Issue by JoseUusitalo** [covcom/205CDE#24]
There was no formatting in the list and the last link was raw:

> - [Tutorial written by Philip Sturgeon](http://code.tutsplus.com/tutorials/working-with-restful-services-in-codeigniter--net-8814) - read this first
> - [Video from Mark Tyers](https://www.youtube.com/watch?v=YevHf8Y11ME) - short introduction how to use CI and Rest Server. Please notice: Rest Server is already installed on the video and at this moment we don't have apigee-program!
> - [REST API Best Practices & Implementing in Codeigniter](http://www.slideshare.net/sachingk30/rest-api-best-practices-implementing-in-codeigniter) - from Slideshare.

Clarification should be added and grammar fixed:

> 1. Read **the** tutorial above and test it with chapter 17's **CodeIgniter** tutorial example

**Comment by iikoo2** [comment]
Corrected...
