### ISSUE TITLE
Found multiple references to Codio

### ISSUE THREAD

**Issue by moccachim** [covcom/205CDE#28]
There is still a reference to Codio in worksheet 3, under the "Audio and video" header.

> The incorporation of videos is similar to audio elements, except for that the corresponding tag is video. For large videos, the file size limit in **Codio** can, however, hinder the use of anything but small video clips.

Also in worksheet 4, near the "Colours" header.

> Next, play with the CSS file. Add new rules and properties to the file and see how they affect the web page. Note that **Codio** helps you in writing the contents of a CSS file by proposing property names and values as you type.

In worksheet 5, in the beginning,

> Notice that as an action it refers to Google’s search engine. It gives a URL where the user’s input data is sent. Open the file in a browser by selecting **Current file (static)**. When you write something into the box and click submit, your text is sent to Google’s search engine.

Current file (static) was how previews worked in Codio, but it isn't the same in Cloud9 and the instruction can be confusing.

**Comment by Diftraku** [comment]
Here's a quick grep of the references to codio:

```
$ grep -r codio ./
./.settings:[codio-bower]
./.settings:; enter your codio-bower preferences here...
Binary file ./.git/index matches
./.gitignore:# codio files
./.gitignore:*.codio
./labs/11 Unit Testing/worksheet.md:Finally load up `SpecRunner.html` in the browser inside codio. You should get a web page indicating that no specs have been found (that’s OK because we have not written any).
./labs/15 RESTful API/worksheet.md:https://museum-austria.codio.io:9500/staffapi/
./labs/15 RESTful API/worksheet.md:https://museum-austria.codio.io:9500.
./labs/15 RESTful API/worksheet.md:https://museum-austria.codio.io:9500/staffapi/persons.
./labs/15 RESTful API/worksheet.md:For instance, suppose a POST request [https://museum-austria.codio.io:9500/staffapi/person?id=13&firstname="Jane"&lastname="Doe"](https://museum-austria.codio.io:9500/staffapi/person?id=13&firstname="Jane"&lastname="Doe") has been obtained by server.
./labs/14 Modular PHP/worksheet.md:-   http://drink-office.codio.io:3000/REST_Client.php?action=get_app&id=1  (drink-office.codio.io:3000 is the host name which may vary.)
./labs/14 Modular PHP/worksheet.md:-   http://drink-office.codio.io:3000/REST_Client.php?action=get_app&id=2
./labs/14 Modular PHP/worksheet.md:-   http://drink-office.codio.io:3000/REST_Client.php?action=get_app&id=3
./labs/14 Modular PHP/worksheet.md:-   http://drink-office.codio.io:3000/REST_Client.php?action=get_app&id=4
./labs/14 Modular PHP/worksheet.md:-   http://drink-office.codio.io:3000/REST_Client.php?action=get_app_list
./labs/19 Document Databases/worksheet.md:https://chrome-coral.codio.io:9500/staff/index.php/Persons/list/
./labs/12 Introduction to PHP/worksheet.md:[apache]: https://codio.com/docs/ide/tutorials/php/
```

Apart from the URLs, the references to Codio should be easily removable. The references in `.settings` are for Codio's Bower, this file may or may not be useful for c9. Also, the entries in .gitignore referencing Codio can be safely removed (and possibly replaced with the ones approriate for c9).

**Comment by Diftraku** [comment]
At commit f1db7356, there are still few lingering references to Codio:

```
$ grep -R codio .
./.gitignore:# codio files
./.gitignore:*.codio
./labs/19 Document Databases/worksheet.md:https://chrome-coral.codio.io:9500/staff/index.php/Persons/list/
```

**Comment by vesavvo** [comment]
Thanks. The remaining references should be fixed now.
