### ISSUE TITLE
Responsive layout with CSS worksheet: CSS property not working on Firefox

### ISSUE THREAD

**Issue by JoseUusitalo** [covcom/205CDE#7]
The first task in the **Test your understanding** exercise is:

> 1. Open file columns.html. Generate a style sheet columnstyles.css where the paragraphs are displayed in: a. two columns b. three columns
>    
>    Hint: search for CSS properties starting with word `column`.

The CSS property being referred to is `column-count`, which does not work on the latest Firefox browser (41.0.2). However it only took me four seconds of Googling to find the correct CSS for Firefox: `-moz-column-count`

So far this is the first instance I've come across where the expected and valid CSS code does not work. Perhaps it would be prudent to teach the students some basics about the differences between browsers and how they handle CSS before this worksheet? At least mention the `-moz-` and `-webkit-` prefixes somewhere to prevent confusion in situations where perfectly valid CSS code does not work.

I was somewhat perplexed that this course did not recommend the use of any specific browser especially since it is teaching CSS and there are entire websites dedicated to this issue: http://caniuse.com/#feat=multicolumn

**Comment by vesavvo** [comment]
Reformatted the assignment to include a mention of browser incosistencies.
