### ISSUE TITLE
Responsive Layout with CSS3 worksheet: Incorrect Bootstrap link

### ISSUE THREAD

**Issue by JoseUusitalo** [covcom/205CDE#8]
Under the **Responsiveness and Bootstrap** heading we are instructed to link the Bootstrap CSS by adding the following code the the HTML file:

``` HTML
<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
```

This code, however, does not work unless **https** is used for the CSS file link. The **game.html** file also already has the correct Bootstrap CSS linking code present.

**Comment by erja** [comment]
Changed the protocol  to https.
